apiVersion: v1
kind: Service
metadata:
  name: {{ include "manufacturing-core-service.fullname" . }}
  labels:
    app: {{ include "manufacturing-core-service.name" . }}
    chart: {{ include "manufacturing-core-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "manufacturing-core-service.name" . }}
    release: {{ .Release.Name }} 